name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Deploy no servidor via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/streamlit-app || git clone https://github.com/${{ github.repository }} ~/streamlit-app && cd ~/streamlit-app
          git pull origin main
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pkill streamlit || true
          nohup streamlit run seu_app.py --server.port 8501 --server.enableCORS false > streamlit.log 2>&1 &

